# Generated by Django 5.0 on 2023-12-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='scientific_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='usage_and_benefits',
            field=models.TextField(default=''),
        ),
    ]
