# Generated by Django 5.0 on 2024-01-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_price_alter_item_scientific_name_and_more'),
        ('item', '0002_alter_item_scientific_name_and_more'),
    ]

    operations = [
    ]
