# Generated by Django 4.2 on 2024-01-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_itemimage_item_discount_item_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_desp',
            field=models.CharField(max_length=900),
        ),
    ]
