# Generated by Django 5.0.1 on 2024-02-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_review_review_desp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_desp',
        ),
    ]
