# Generated by Django 5.0.1 on 2024-02-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_price'),
        ('item', '0006_remove_review_review_desp'),
    ]

    operations = [
    ]
