# Generated by Django 5.0 on 2024-02-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='bill_pdfs/'),
        ),
    ]
