# Generated by Django 5.0 on 2024-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_bill_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='contact_info',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
