# Generated by Django 5.0 on 2024-01-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='core/images/default_user.png', null=True, upload_to='profile_pics/'),
        ),
    ]
