# Generated by Django 5.0 on 2024-01-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='core/images/default_user.png', null=True, upload_to='media/'),
        ),
    ]
