# Generated by Django 5.0 on 2024-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
