# Generated by Django 5.0 on 2024-01-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerform', '0002_selleraccount_bio_selleraccount_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleraccount',
            old_name='user',
            new_name='user1',
        ),
    ]
