# Generated by Django 4.2 on 2024-01-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerform', '0003_rename_user_selleraccount_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleraccount',
            old_name='user1',
            new_name='user',
        ),
    ]
