# Generated by Django 4.2 on 2024-01-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerform', '0004_rename_user1_selleraccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='selleraccount',
            name='location',
        ),
    ]
